### ISSUE TITLE
Support for `default_role = "any"`

### ISSUE THREAD

**Issue by Julian** [stsewd/sphinx.nvim#10]
You may already be planning this, but for projects where [`default_role = "any"`, as suggested by the Sphinx docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-any), one can write \`foo\` and have whichever role \`foo\` is be automatically discovered.

In such a case it'd be great to be able to get completions after only typing \` -- as is it seems I need to explicitly type `:doc:..`, do the completion, then delete the explicit role.

(Example project of mine: https://github.com/Julian/regret/)

**Comment by stsewd** [comment]
That's a great idea, I think we can have a setting for the default role and default to `any`.
