### ISSUE TITLE
E117: Unknown function: SphinxListFiles

### ISSUE THREAD

**Issue by SilverRainZ** [stsewd/sphinx.nvim#16]
I installed sphinx.nvim as README said, and also have fzf.vim installed. When I try `:SphinxFiles`:

```
Error detected while processing function sphinx#list_files:                                                                                   
line    3:
E117: Unknown function: SphinxListFiles
E15: Invalid expression: SphinxListFiles()
```

Tunction 
```
$ cd ~/.local/share/nvim/plugged/sphinx.nvim
$ grep -r SphinxListFiles               
autoload/sphinx.vim:  let l:results = SphinxListFiles()
autoload/sphinx.vim:    let l:results = SphinxListFiles()
rplugin/python3/sphinx_nvim/__init__.py:    @pynvim.function("SphinxListFiles", sync=True)
```

---

- Archlinux
- neovim 0.4.4
- pynvim 0.4.3-1
- latest sphinx.vim

**Comment by stsewd** [comment]
@SilverRainZ hi, did you try running `:UpdateRemotePlugins`?

**Comment by stsewd** [comment]
Also, maybe do you have the `g:fzf_command_prefix` setting set? If so, the command will use that prefix.

**Comment by SilverRainZ** [comment]
It should be done by vim-plug?

I try this command and now it works :joy:

**Comment by stsewd** [comment]
> It should be done by vim-plug?
> 
> I try this command and now it works joy

Yeah, you can use `Plug 'stsewd/sphinx.nvim', { 'do': ':UpdateRemotePlugins' }` as shown in the readme.

**Comment by SilverRainZ** [comment]
I actually use `Plug 'stsewd/sphinx.nvim', { 'do': ':UpdateRemotePlugins' ` but it doesn't work.

Anyway it works when I manaually run `:UpdateRemotePlugins`, thank you!
